# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScannerFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  flutter_application_path = '../scanner_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)
  # Pods for ScannerFlutter

  target 'ScannerFlutterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScannerFlutterUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
