# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # Step para incrementar la versión tambien se puede tomar de los pr
    increment_build_number(xcodeproj: "ScannerFlutter.xcodeproj")
    # Step para Compilar 
    gym(workspace: "ScannerFlutter.xcworkspace", scheme: "ScannerFlutter")
    # Step para Publicar en TF. 
    pilot(skip_metadata: true, skip_screenshots: true)
  end
end
